[package]
name = "openmm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
byteorder = "1.4.3"
flate2 = "1.0.26"
image = "0.24.6"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
