[package]
name = "rmm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
byteorder = "1.4.3"
flate2 = "1.0.26"
image = "0.24.6"
